ALTER TABLE `gameobject_template`
ADD COLUMN `data24` INT(10) UNSIGNED DEFAULT '0' NOT NULL AFTER `data23`,
ADD COLUMN `data25` INT(10) UNSIGNED DEFAULT '0' NOT NULL AFTER `data24`,
ADD COLUMN `data26` INT(10) UNSIGNED DEFAULT '0' NOT NULL AFTER `data25`,
ADD COLUMN `data27` INT(10) UNSIGNED DEFAULT '0' NOT NULL AFTER `data26`,
ADD COLUMN `data28` INT(10) UNSIGNED DEFAULT '0' NOT NULL AFTER `data27`,
ADD COLUMN `data29` INT(10) UNSIGNED DEFAULT '0' NOT NULL AFTER `data28`,
ADD COLUMN `data30` INT(10) UNSIGNED DEFAULT '0' NOT NULL AFTER `data29`,
ADD COLUMN `data31` INT(10) UNSIGNED DEFAULT '0' NOT NULL AFTER `data30`,
ADD COLUMN `unk2` INT(3) UNSIGNED DEFAULT '0' NOT NULL AFTER `data31`;